### ISSUE TITLE
Linux Installation warning that dotnet version is wrong

### ISSUE THREAD

**Issue by knoxyca** [Jaykul/Jupyter-PowerShell#9]
Install script failing in multiple ways on Linux.

Having the latest dotnet isntalled, gives an error that you're not on the expected version.
```
PS /home/corbob/Jupyter-PowerShell> ./Install.ps1 -KernelFolder ~/.jupyter/kernel                                                                                        
WARNING: 
            The currently installed 'dotnet' (.NET Command Line Tools) is not the expected version.

            Installed version: 2.0.0-preview2-006127
            Expected version: 2.0.0-preview1-005977

            If your version is older, you PROBABLY cannot run the 'PowerShell (Core)' kernel.

            Get the latest version from https://www.microsoft.com/net/core/preview
            

            
/usr/bin/mkdir: invalid option -- 'P'
Try '/usr/bin/mkdir --help' for more information.

```
This doesn't seem to stop the installation, but it is a warning that comes up.

**Comment by Jaykul** [comment]
Yeah. Preview2 _just_ came out last week...

I'll upgrade my dev box to Preview2 tonight and change that warning to be the other way around ...

**Comment by Jaykul** [comment]
I'm closing this -- the `mkdir` error was handled elsewhere, and this warning is going to stick around -- the new "semantic" versions are nigh impossible to compare.
